services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow ui
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
    ports:
      - "5000:5000"

  server:
    build: ./server/normal
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: always
