name: Build & Deploy to VM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image
      run: |
        IMAGE=${{ secrets.IMAGE_NAME }}
        SHA=$(echo "${GITHUB_SHA}" | head -c 8)
        docker build -t "${IMAGE}:sha-${SHA}" -t "${IMAGE}:latest" .
        docker push "${IMAGE}:sha-${SHA}"
        docker push "${IMAGE}:latest"